services:
  web:
    volumes:
      - ./services/web:/app
      - /app/.venv
    working_dir: /app
    environment:
      - MODE=dev
      - PYTHONPATH=/app

  auth:
    volumes:
      - ./services/auth:/app
      - /app/.venv
    working_dir: /app
    environment:
      - MODE=dev
      - PYTHONPATH=/app

  admin:
    volumes:
      - ./services/admin:/app
      - /app/.venv
    working_dir: /app
    environment:
      - MODE=dev
      - PYTHONPATH=/app

