services:
  web:
    volumes:
      - ./services/web:/app
    working_dir: /app
    environment:
      - MODE=dev
      - PYTHONPATH=/src

  auth:
    volumes:
      - ./services/auth:/app
    environment:
      - MODE=dev

  admin:
    volumes:
      - ./services/admin:/app
    environment:
      - MODE=dev
