services:
  web:
    build:
      context: services/web
      dockerfile: Dockerfile
      target: prod
    environment:
      - TZ=Europe/Moscow
    ports:
      - "8100:8100"
    command: python3 start.py
    env_file:
      - .env
    depends_on:
      - postgres

  auth:
    build:
      context: services/auth
      dockerfile: Dockerfile
      target: prod
    environment:
      - TZ=Europe/Moscow
    ports:
      - "8001:8001"
    command: python3 start.py
    env_file:
      - .env
    depends_on:
      - postgres

  admin:
    build:
      context: services/admin
      dockerfile: Dockerfile
      target: prod
    environment:
      - TZ=Europe/Moscow
    ports:
      - "8002:8002"
    command: python3 start.py
    env_file:
      - .env
    depends_on:
      - postgres

  planner:
    build:
      context: services/planner
      dockerfile: Dockerfile
      target: prod
    environment:
      - TZ=Europe/Moscow
    ports:
      - "8003:8003"
    command: python3 start.py
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      TZ: Europe/Moscow
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./infra/postgres/data:/var/lib/postgresql/data
      - ./infra/postgres/scripts:/var/lib/postgresql/scripts

  gateway:
    build:
      context: infra/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - web
      - auth
      - admin
      - planner
